Repository dothereum/dothereum, pull requests merged in 2019-12, with the labels that each got.

#66 deps: bump substrate to latest master
  Cargo.lock
  runtime/src/impls.rs
  runtime/src/lib.rs
Labels: pr9-good

#65 docs: write a readme
  CONTRIBUTING.md
  README.md
Labels: i8-documentation, pr9-good

#69 applying substrate changes
  Cargo.lock
  cli/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: pr9-good

#67 deps: update substrate names
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/bin/main.rs
  cli/build.rs
  cli/src/chain_spec.rs
  cli/src/cli.rs
  cli/src/factory_impl.rs
  cli/src/service.rs
  executor/Cargo.toml
  executor/src/lib.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/Cargo.toml
  runtime/src/impls.rs
  runtime/src/lib.rs
  testing/Cargo.toml
  testing/src/client.rs
  testing/src/genesis.rs
  testing/src/keyring.rs
Labels: pr9-good

#72 deps: daily substrate bump
  Cargo.lock
  cli/Cargo.toml
  cli/src/service.rs
Labels: pr0-review

#73 beta: daily substrate bump
  Cargo.lock
  Cargo.toml
  build.rs
  runtime/Cargo.lock
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
  src/chain_spec.rs
  src/cli.rs
  src/main.rs
  src/service.rs
Labels: pr0-review

#74 gamma: daily substrate bump
  Cargo.lock
  cli/Cargo.toml
  cli/src/chain_spec.rs
  runtime/Cargo.toml
  runtime/src/impls.rs
  runtime/src/lib.rs
Labels: pr9-good
